# Generated by Django 3.2.10 on 2022-02-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb',
            field=models.ImageField(default='default_product.jpg', null=True, upload_to=''),
        ),
    ]
